kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: my-dg-template
objects:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: datagrid
  spec:
    targetNamespaces:
    - dgdemo

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: datagrid-operator
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    channel: 8.2.x
    installPlanApproval: Automatic
    name: datagrid
    source: redhat-operators
    sourceNamespace: openshift-marketplace

- apiVersion: infinispan.org/v1
  kind: Infinispan
  metadata:
    name: datagrid-service
    namespace: dgdemo
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    replicas: 2

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: my-dg
  spec:
    to:
      kind: Service
      name: datagrid-service
      weight: 100
    port:
      targetPort: infinispan
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Allow
    wildcardPolicy: None

- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: mycachedefinition
  spec:
    clusterName: datagrid-service
    name: mycache